export { default as Layers } from './Layers/Layers'
export { default as IntroInfo } from './IntroInfo/IntroInfo'
export { default as Header } from './Header/Header'
export { default as DetailForm } from './DetailForm/DetailForm'
export { default as HomeInfo } from './HomeInfo/HomeInfo'
