export { default as Intro } from './Intro/Intro'
export { default as School } from './School/School'
export { default as Home } from './Home/Home'
export { default as Detail } from './Detail/Detail'
export { default as Error } from './Error/Error'
